branch-defaults:
  default:
    environment: flask-backend-env
    group_suffix: null
global:
  application_name: flask-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
